### ISSUE TITLE
토큰 정리

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#64]
https://github.com/xfrnk2/1d1c/blob/fcf023b98592efd538ec1d4da545b94852ec7913/.travis.yml#L10

@xfrnk2 이 파일에 있는 토큰은 제 travis-ci의 encrypted token인데,  
sonar-cloud를 이용하여 다시 설정하고 토큰도 필요한 값으로 수정하면 좋겠네요.

이 참에 travis-cli 사용법도 익히시고요~

**Comment by xfrnk2** [comment]
넵 감사합니다.

**Comment by xfrnk2** [comment]
@zrma 
sonar-cloud와 연동은 잘 되었어요. 그런데 위의 언급하신 .travis.yml 줄은 어떤 방식으로 수정해야 할지 감이 잘 안잡혀요. 
현재 travis-ci 파일 안에..

```
script:
- sonar-scanner -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN

addons:
  sonarcloud:
    organization: "xfrnk2-github"
    token:
      secure: "**************************" # encrypted value of your token

```
위처럼 sonar에 대한 부분이 둘 있는데, 겹쳐도 괜찮은 걸까요?
